version: '2'

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4

  complex-logic:
    enabled: true
    config:
      threshold: 4

  file-lines:
    enabled: true
    config:
      threshold: 250

  method-complexity:
    enabled: true
    config:
      threshold: 5

  method-count:
    enabled: true
    config:
      threshold: 20

  method-lines:
    enabled: true
    config:
      threshold: 25

  nested-control-flow:
    enabled: true
    config:
      threshold: 4

  return-statements:
    enabled: true
    config:
      threshold: 4

  similar-code:
    enabled: true

  identical-code:
    enabled: true

plugins:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript

  eslint:
    enabled: true
    channel: 'eslint-6'
    config:
      extensions:
        - .js
        - .json
        - .jsx
        - .ts
        - .tsx

  tslint:
    enabled: false

  stylelint:
    enabled: false

  fixme:
    enabled: false

ratings:
  paths:
    - 'src/**/*.{ts,tsx,js,jsx,json}'

exclude_paths:
  - .build
  - .cache
  - .env
  - .github
  - .ignore
  - .reports
  - .vscode
  - 3rdparty
  - cypress
  - data
  - node_modules
  - src/.generated
  - src/assets
  - static
  - tsconfig.json
